version: 2
jobs:
  hello:
    docker:
      - image: circleci/python:3.8.6
    steps:
      - checkout
      - run: cd backend && python -m pytest test

workflows:
  version: 2
  workflow:
    jobs:
    - hello
