version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.cpu
      args:
        user_name: $user_name
        group_name: $group_name
    image: $image_name
    container_name: $container_name
    tty: true
    volumes:
      - .:/home/$user_name/workspace
    working_dir: /home/$user_name/workspace
    ports:
      - "4141:4141"   # kedro-viz
      - "5000:5000"   # MLflow
      - "6006:6006"   # tensorboard

