version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.cpu
      args:
        user_name: $user_name
        group_name: $group_name
    image: $image_name
    container_name: $container_name
    tty: true
    volumes:
      - .:/home/$user_name/workspace
    working_dir: /home/$user_name/workspace
    sysctls:
      - net.core.somaxconn=$somaxconn
      - net.ipv4.tcp_syncookies=0
    ports:
      - "5000:5000"   # MLflow
      - "6006:6006"   # tensorboard
      - "8000:8000"   # webapi
      - "8080:8080"   # vue
